version: '3.9'

services:
  db:
    container_name: db
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=credit_base
      - POSTGRES_PASSWORD=root
    image: postgres:latest
    networks:
      - creditNetwork

  app:
    container_name: credit
    image: exzombie/credit:v1
    ports:
    - "8080:8080"
    environment:
     - DB_HOST=db
    depends_on:
      - db
    networks:
      - creditNetwork

networks:
  creditNetwork:



